[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200
  force = true

[functions]
  directory = "."
  included_files = ["app.py", "templates/**", "static/**"]